jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: matrix.os == 'windows-latest'
      name: Configure Git
      run: 'git config --global core.longpaths true

        '
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      if: matrix.os == 'windows-latest'
      name: Build with Maven in Windows
      run: './mvnw --batch-mode --no-transfer-progress ''-Dmaven.javadoc.skip=true''
        clean install

        '
    - continue-on-error: true
      if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
      name: Build with Maven in Linux or macOS
      run: './mvnw --batch-mode --no-transfer-progress ''-Dmaven.javadoc.skip=true''
        clean install -Pcheck

        '
    - continue-on-error: true
      if: matrix.os == 'ubuntu-latest' && matrix.java == '8'
      name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: '**/target/site/jacoco/jacoco.xml'
    strategy:
      matrix:
        java:
        - 8
        - 17
        - 21
        os:
        - windows-latest
        - macos-latest
        - ubuntu-latest
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
