concurrency:
  cancel-in-progress: true
  group: check-${{ github.workflow }}-${{ github.ref }}
jobs:
  check-checkstyle:
    name: Check - CheckStyle
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Run CheckStyle
      run: ./mvnw checkstyle:check -Pcheck -T1C
    timeout-minutes: 10
  check-license:
    name: Check - License
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Run Apache Rat
      run: ./mvnw apache-rat:check -Pcheck -T1C
    timeout-minutes: 10
  check-spotless:
    name: Check - Spotless
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Run Spotless
      run: ./mvnw spotless:check -Pcheck -T1C
    timeout-minutes: 10
name: Required - Check
on:
  repository_dispatch:
    types: trigger-ga___required-check.yml
